version: "3"
services:
  frontend:
    build: frontend
    networks:
      - rpgapp
    image: frontend:local
    command: yarn dev
    depends_on:
    - api
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/.:/opt/frontend
      - ./frontend/internal_node_modules:/opt/frontend/node_modules/
  api:
    build:
      context: api
      args:
        NODE_ENV: "development"
    networks:
      - rpgapp
    image: api:local
    command: yarn run start
    depends_on:
      - db
    env_file:
      - ./api/.env
    ports:
      - '8080:3000'
    volumes:
      - ./api:/opt/app
      - ./api/package.json:/opt/app/package.json
      - ./api/yarn.lock:/opt/app/yarn.lock
  db:
    image: postgres:11
    networks:
      - rpgapp
    environment:
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_DB=rpg
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - '8001:5432'
networks:
  rpgapp:
